name: Update CHANGES File
on:
  push:
    paths-ignore:
      - 'CHANGES'
    branches:
      - master
jobs:
  update-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Update CHANGES file
        run: |
          echo '1s/^/* ${{  TITLE	 }}. Thanks @${{ github.actor }}\n/' CHANGES
# sed -i '1s/^/* ${{ github.event.pull_request.title }}. Thanks @${{ github.actor }}\n/' CHANGES
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          message: ${{ github.event.pull_request.title }}