name: Update CHANGES File
on:
  pull_request:
    types: [opened]
    branches:
      - master
    paths-ignore:
      - 'CHANGES'
jobs:
  update-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Update CHANGES file
        run: |
          echo "${{ github.event.pull_request.title }}"
          echo "* ${{ github.event.pull_request.title }}" Thanks @${{ github.actor }} > CHANGES2
          cat CHANGES >> CHANGES2
          mv CHANGES2 CHANGES
# sed -i '1s/^/* $PR_TITLE. Thanks @${{ github.actor }}\n/' CHANGES
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
          message: "Update CHANGES file"
