name: Update CHANGES File
on:
  push:
    paths-ignore:
      - 'CHANGES'
    branches:
      - master
jobs:
  update-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Update CHANGES file
        run: |
          COMMIT="${{ github.event.head_commit.message }}"
          PR_TITLE=`echo "${COMMIT}" | head -n 1`
          echo "1s/^/* ${PR_TITLE}" Thanks @${{ github.actor }} > CHANGES2
          cat CHANGES >> CHANGES2
          mv CHANGES2 CHANGES
# sed -i '1s/^/* $PR_TITLE. Thanks @${{ github.actor }}\n/' CHANGES
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          message: ${{ github.event.head_commit.message }}
